# -*- coding: utf-8 -*-
"""ranking_filmow_12_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GoKdutXFTR_9FudL4Raxt0wu0C9uUy0P
"""

import pandas as pd

unames = ['user_id','gender','age','occupation','zip']
users = pd.read_table('dane/users.dat',engine='python', sep='::',header=None,names=unames)

rnames = ['user_id','movie_id','rating','timestamp']
ratings = pd.read_table('dane/ratings.dat',engine='python',sep='::',header=None,names=rnames)

mnames = ['movie_id','title','genres']
movies = pd.read_table('dane/movies.dat',encoding='ISO-8859-1', engine='python',sep='::',header=None,names=mnames)

users[:5]

ratings[:5]

movies[:5]

data = pd.merge(pd.merge(ratings,users),movies)
data
#wynik = pd.merge(ratings,users,on='ID',how='inner')
#wynik = pd.merge(ratings,users,left_on='ID',right_on='ID_usr',how='inner')

mean_ratings = data.pivot_table('rating',index='title',columns='gender',aggfunc='mean')
mean_ratings[:5]

ratings_by_title = data.groupby('title').size()
ratings_by_title[:10]

active_titles = ratings_by_title.index[ratings_by_title>=250]
active_titles

mean_ratings = mean_ratings.loc[active_titles]
mean_ratings[:10]

top_female_ratings = mean_ratings.sort_values(by='F', ascending=False)
top_female_ratings[:10]

mean_ratings['diff'] = mean_ratings['M'] - mean_ratings['F']

sorted_by_diff = mean_ratings.sort_values(by='diff')
sorted_by_diff[:10]

sorted_by_diff[::-1][:10]

ratings_std_by_title = data.groupby('title')['rating'].std()
ratings_std_by_title = ratings_std_by_title.loc[active_titles]
ratings_std_by_title.sort_values(ascending=False)[:10]